//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSTWebsite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSTWebsite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 651 Stone Road, Benicia.
        /// </summary>
        public static string CompanyAddressLineOne {
            get {
                return ResourceManager.GetString("CompanyAddressLineOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California 94510, United States of America.
        /// </summary>
        public static string CompanyAddressLineTwo {
            get {
                return ResourceManager.GetString("CompanyAddressLineTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1(707) 745-8952.
        /// </summary>
        public static string CompanyMainFax {
            get {
                return ResourceManager.GetString("CompanyMainFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1(707) 745-5117.
        /// </summary>
        public static string CompanyMainPhone {
            get {
                return ResourceManager.GetString("CompanyMainPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST Controls.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1(800) 251-0773.
        /// </summary>
        public static string CompanyTollFree {
            get {
                return ResourceManager.GetString("CompanyTollFree", resourceCulture);
            }
        }
    }
}
